[package]
name = "wireguard_demo"
version = "0.1.0"
edition = "2021"

publish = false

[dependencies]
common = {path = "../../common", version = "0.1.0" }
controller = {path = "../../controller", version = "0.1.0" }
anyhow = "1.0.45"
base64 = "0.13.0"
